export default {
  title: 'Project',
  name: 'project',
  type: 'document',
  description: 'A customer project',
  fields: [
    {
      title: 'Title',
      name: 'title',
      type: 'string',
      description: 'The title of the project',
      validation: (R) => R.required(),
    },
    {
      title: 'Path',
      name: 'path',
      type: 'slug',
      description: 'The unique url name for the project',
      validation: (R) => R.required(),
      options: {
        source: 'title',
      },
    },
    {
      title: 'Subtitle',
      name: 'subTitle',
      type: 'string',
      description: 'The subtitle of the project',
      validation: (R) => R.required(),
    },
    {
      title: 'Description',
      name: 'description',
      type: 'string',
      description: 'The description of the project',
      validation: (R) => R.required(),
    },
    {
      title: 'Main image',
      name: 'mainImage',
      type: 'image',
      description: 'The main image of the project',
    },
    {
      title: 'Categories',
      name: 'categories',
      type: 'array',
      of: [{ type: 'reference', to: { type: 'category' } }],
      description: 'The category of the project',
      validation: (R) => R.required(),
    },
    {
      title: 'Tags',
      name: 'tags',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'The tags of the project',
      options: {
        layout: 'tags',
      },
    },
    {
      title: 'Content',
      name: 'content',
      type: 'array',
      description: 'Content of the project',
      of: [{ type: 'block' }, { type: 'image' }],
      validation: (R) => R.required(),
    },
  ],
};
