/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: 'span';
    _key: string;
  }>;
  style?: 'normal';
  listItem?: never;
  markDefs?: Array<{
    href: string;
    _type: 'link';
    _key: string;
  }>;
  level?: number;
  _type: 'block';
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type EmployeeReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'employee';
};

export type Studio = {
  _id: string;
  _type: 'studio';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  pageContent?: RichText;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  sortedEmployees?: Array<
    {
      _key: string;
    } & EmployeeReference
  >;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type ProjectReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'project';
};

export type CategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'category';
};

export type Settings = {
  _id: string;
  _type: 'settings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  email: string;
  phone: string;
  address: Array<string>;
  emailJob: string;
  logotype: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  featuredProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  categoriesOrder: Array<
    {
      _key: string;
    } & CategoryReference
  >;
};

export type Employee = {
  _id: string;
  _type: 'employee';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  email?: string;
  phone?: string;
  titles?: string;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  subTitle: string;
  textBody: RichText;
  assignment?: Array<string>;
  location?: string;
  clients?: Array<string>;
  size?: string;
  collaborators?: Array<string>;
  year?: string;
  awards?: Array<string>;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  categories: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  path: Slug;
  credits?: string;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  path: Slug;
  sortedProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type MediaFolderReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'media.folder';
};

export type MediaFolder = {
  _id: string;
  _type: 'media.folder';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: MediaFolderReference;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | RichText
  | SanityImageAssetReference
  | EmployeeReference
  | Studio
  | SanityImageCrop
  | SanityImageHotspot
  | ProjectReference
  | CategoryReference
  | Settings
  | Employee
  | Project
  | Slug
  | Category
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../site/src/services/sanity.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "settings"][0]{..., "logotype":logotype.asset->,featuredProjects[defined(@->_id)]->{..., "mainImage":mainImage.asset->, categories[]->}, categoriesOrder[defined(@->_id)]->{...}}
export type SETTINGS_QUERY_RESULT = {
  _id: string;
  _type: 'settings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  email: string;
  phone: string;
  address: Array<string>;
  emailJob: string;
  logotype: {
    _id: string;
    _type: 'sanity.imageAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash: string;
    extension: string;
    mimeType: string;
    size: number;
    assetId: string;
    uploadId?: string;
    path: string;
    url: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
  } | null;
  featuredProjects: Array<{
    _id: string;
    _type: 'project';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    subTitle: string;
    textBody: RichText;
    assignment?: Array<string>;
    location?: string;
    clients?: Array<string>;
    size?: string;
    collaborators?: Array<string>;
    year?: string;
    awards?: Array<string>;
    mainImage: {
      _id: string;
      _type: 'sanity.imageAsset';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    categories: Array<{
      _id: string;
      _type: 'category';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title: string;
      path: Slug;
      sortedProjects?: Array<
        {
          _key: string;
        } & ProjectReference
      >;
    }>;
    images?: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
      _key: string;
    }>;
    path: Slug;
    credits?: string;
  }> | null;
  categoriesOrder: Array<{
    _id: string;
    _type: 'category';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    path: Slug;
    sortedProjects?: Array<
      {
        _key: string;
      } & ProjectReference
    >;
  }>;
} | null;

// Source: ../site/src/services/sanity.ts
// Variable: CATEGORY_QUERY
// Query: *[_type == "category" && path.current == $slug][0]{..., sortedProjects[defined(@->_id)]->{..., "mainImage":mainImage.asset->, categories[]->}}
export type CATEGORY_QUERY_RESULT = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  path: Slug;
  sortedProjects: Array<{
    _id: string;
    _type: 'project';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    subTitle: string;
    textBody: RichText;
    assignment?: Array<string>;
    location?: string;
    clients?: Array<string>;
    size?: string;
    collaborators?: Array<string>;
    year?: string;
    awards?: Array<string>;
    mainImage: {
      _id: string;
      _type: 'sanity.imageAsset';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    categories: Array<{
      _id: string;
      _type: 'category';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title: string;
      path: Slug;
      sortedProjects?: Array<
        {
          _key: string;
        } & ProjectReference
      >;
    }>;
    images?: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
      _key: string;
    }>;
    path: Slug;
    credits?: string;
  }> | null;
} | null;

// Source: ../site/src/services/sanity.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"]{..., "mainImage":mainImage.asset->, categories[]->, images[]{...,asset->}}
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  subTitle: string;
  textBody: RichText;
  assignment?: Array<string>;
  location?: string;
  clients?: Array<string>;
  size?: string;
  collaborators?: Array<string>;
  year?: string;
  awards?: Array<string>;
  mainImage: {
    _id: string;
    _type: 'sanity.imageAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash: string;
    extension: string;
    mimeType: string;
    size: number;
    assetId: string;
    uploadId?: string;
    path: string;
    url: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
  } | null;
  categories: Array<{
    _id: string;
    _type: 'category';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    path: Slug;
    sortedProjects?: Array<
      {
        _key: string;
      } & ProjectReference
    >;
  }>;
  images: Array<{
    asset: {
      _id: string;
      _type: 'sanity.imageAsset';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }> | null;
  path: Slug;
  credits?: string;
}>;

// Source: ../site/src/services/sanity.ts
// Variable: PROJECTS_BY_CATEGORY_QUERY
// Query: *[_type == "project" && references($category)] | order(year desc) {_id, title, path, subTitle, description, "mainImage":mainImage.asset->, categories[]->}
export type PROJECTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  path: Slug;
  subTitle: string;
  description: null;
  mainImage: {
    _id: string;
    _type: 'sanity.imageAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash: string;
    extension: string;
    mimeType: string;
    size: number;
    assetId: string;
    uploadId?: string;
    path: string;
    url: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
  } | null;
  categories: Array<{
    _id: string;
    _type: 'category';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    path: Slug;
    sortedProjects?: Array<
      {
        _key: string;
      } & ProjectReference
    >;
  }>;
}>;

// Source: ../site/src/services/sanity.ts
// Variable: EMPLOYEES_QUERY
// Query: *[_type == "employee"] | order(name asc) {_id, name, email, phone, titles, "image":image.asset->}
export type EMPLOYEES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  email: string | null;
  phone: string | null;
  titles: string | null;
  image: {
    _id: string;
    _type: 'sanity.imageAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash: string;
    extension: string;
    mimeType: string;
    size: number;
    assetId: string;
    uploadId?: string;
    path: string;
    url: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
  } | null;
}>;

// Source: ../site/src/services/sanity.ts
// Variable: STUDIO_QUERY
// Query: *[_type == "studio"][0]{...,"employees":sortedEmployees[defined(@->_id)]->{_id, name, email, phone, titles, "image":image.asset->}}
export type STUDIO_QUERY_RESULT = {
  _id: string;
  _type: 'studio';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  pageContent?: RichText;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  sortedEmployees?: Array<
    {
      _key: string;
    } & EmployeeReference
  >;
  employees: Array<{
    _id: string;
    name: string;
    email: string | null;
    phone: string | null;
    titles: string | null;
    image: {
      _id: string;
      _type: 'sanity.imageAsset';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  }> | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "settings"][0]{..., "logotype":logotype.asset->,featuredProjects[defined(@->_id)]->{..., "mainImage":mainImage.asset->, categories[]->}, categoriesOrder[defined(@->_id)]->{...}}': SETTINGS_QUERY_RESULT;
    '*[_type == "category" && path.current == $slug][0]{..., sortedProjects[defined(@->_id)]->{..., "mainImage":mainImage.asset->, categories[]->}}': CATEGORY_QUERY_RESULT;
    '*[_type == "project"]{..., "mainImage":mainImage.asset->, categories[]->, images[]{...,asset->}}': PROJECTS_QUERY_RESULT;
    '*[_type == "project" && references($category)] | order(year desc) {_id, title, path, subTitle, description, "mainImage":mainImage.asset->, categories[]->}': PROJECTS_BY_CATEGORY_QUERY_RESULT;
    '*[_type == "employee"] | order(name asc) {_id, name, email, phone, titles, "image":image.asset->}': EMPLOYEES_QUERY_RESULT;
    '*[_type == "studio"][0]{...,"employees":sortedEmployees[defined(@->_id)]->{_id, name, email, phone, titles, "image":image.asset->}}': STUDIO_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
