// Shapes returned by the queries in services/sanity.ts. The underlying types
// are generated by `pnpm typegen` in studio/.
import type {
  EMPLOYEES_QUERY_RESULT,
  PROJECTS_BY_CATEGORY_QUERY_RESULT,
  PROJECTS_QUERY_RESULT,
  SETTINGS_QUERY_RESULT,
  STUDIO_QUERY_RESULT,
} from './sanity.types';

export type Settings = NonNullable<SETTINGS_QUERY_RESULT>;
export type Category = Settings['categoriesOrder'][number];
/** A project with everything its own page renders. */
export type Project = PROJECTS_QUERY_RESULT[number];
/** The fields a project card renders; every project query includes them. */
export type ProjectSummary = Pick<
  PROJECTS_BY_CATEGORY_QUERY_RESULT[number],
  '_id' | 'title' | 'path' | 'mainImage'
>;
export type Employee = EMPLOYEES_QUERY_RESULT[number];
export type Studio = NonNullable<STUDIO_QUERY_RESULT>;
export type ImageAsset = NonNullable<Project['mainImage']>;
